services:
  banking-db:
    image: postgres:14-alpine
    container_name: banking_postgres_db
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=banking_db
    ports:
      - "5432:5432"
    volumes:
      - banking_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d banking_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  airflow-db:
    image: postgres:14-alpine
    container_name: airflow_postgres_db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
    volumes:
      - airflow_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  airflow-init:
    image: apache/airflow:2.8.1
    container_name: banking_airflow_init
    depends_on:
      airflow-db:
        condition: service_healthy
      banking-db:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./src:/opt/airflow/src
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install --no-cache-dir psycopg2-binary Faker && \
        airflow db init && \
        airflow users create \
          --username airflow \
          --password airflow \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_UID=50000

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: banking_airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - ./dags_or_jobs:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./src:/opt/airflow/src
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_UID=50000
      - BANKING_DB_HOST=banking-db
      - BANKING_DB_PORT=5432
      - BANKING_DB_NAME=banking_db
      - BANKING_DB_USER=db_user
      - BANKING_DB_PASSWORD=db_password
      - _PIP_ADDITIONAL_REQUIREMENTS=psycopg2-binary Faker
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: banking_airflow_scheduler
    command: scheduler
    depends_on:
      airflow-webserver:
        condition: service_healthy
    volumes:
      - ./dags_or_jobs:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./src:/opt/airflow/src
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_UID=50000
      - BANKING_DB_HOST=banking-db
      - BANKING_DB_PORT=5432
      - BANKING_DB_NAME=banking_db
      - BANKING_DB_USER=db_user
      - BANKING_DB_PASSWORD=db_password
      - _PIP_ADDITIONAL_REQUIREMENTS=psycopg2-binary Faker
    restart: unless-stopped

volumes:
  banking_data:
  airflow_data:

