

services:
  db:
    image: postgres:17-alpine
    container_name: banking_postgres_db
  
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: banking_db
    
    ports:
      - "5432:5432"
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/init.sql

# Defines the named volume for data persistence
volumes:
  postgres_data:
    driver: local

